language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "6.1"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
notifications:
  slack: eternitywall:1neJuTEDaApxu3A68ojcHBwG
